extends: eslint:recommended

env:
  es6: true
  browser: true
  amd: true

globals:
  module: false
  process: false
  root: false
  webpack: false
  __dirname: false
  __DEV__: false

parser:
  babel-eslint

settings:
  import/extensions:
  - ".jsx?"
  import/ignore:
  - node_modules
  - ".json$"

plugins: [
  react
]

parserOptions:
  sourceType: module
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true

rules:
  no-unused-vars: 1
  no-debugger: 1
  no-console: 1
  react/jsx-uses-react: 1
  react/jsx-uses-vars: 1
  no-mixed-spaces-and-tabs: 1
  indent:
    - error
    - tab
  semi:
    - error
    - never

