export const SHOW_SUBSCRIPTION_POPUP = 'SHOW_SUBSCRIPTION_POPUP'
export const SHOW_SUBSCRIPTION_POPUP_RESULT = 'SHOW_SUBSCRIPTION_POPUP_RESULT'
export const SHOW_SURVEY_POPUP = 'SHOW_SURVEY_POPUP'
export const SHOW_SURVEY_POPUP_RESULT = 'SHOW_SURVEY_POPUP_RESULT'

